import * as Joi from 'joi';

export const validationSchema = Joi.object({
  NODE_ENV: Joi.string().valid('development', 'production', 'test').default('development'),
  PORT: Joi.number().default(3001),
  CORS_ORIGIN: Joi.string().default('http://localhost:5173'),
  DATABASE_URL: Joi.string().required(),
  REDIS_URL: Joi.string().uri().optional(),
  JWT_ACCESS_SECRET: Joi.string().min(32).required(),
  JWT_ACCESS_EXPIRATION: Joi.string().default('15m'),
  JWT_REFRESH_EXPIRATION: Joi.string().default('7d'),
  RAZORPAY_KEY_ID: Joi.string().optional(),
  RAZORPAY_KEY_SECRET: Joi.string().optional(),
  RAZORPAY_WEBHOOK_SECRET: Joi.string().optional(),
  STRIPE_SECRET_KEY: Joi.string().optional(),
  STRIPE_WEBHOOK_SECRET: Joi.string().optional(),
  STRIPE_PUBLISHABLE_KEY: Joi.string().optional(),
  SUPER_ADMIN_EMAILS: Joi.string()
    .optional()
    .description('Comma-separated list of super admin emails'),
  AI_DEFAULT_PROVIDER: Joi.string().default('openai'),
  AI_TEMPERATURE: Joi.number().default(0.7),
  AI_TIMEOUT: Joi.number().default(30000),
  AI_RETRIES: Joi.number().default(3),
  AI_STREAMING: Joi.boolean().default(true),
  OPENAI_API_KEY: Joi.string().optional(),
  OPENAI_DEFAULT_MODEL: Joi.string().default('gpt-4o'),
  GEMINI_API_KEY: Joi.string().optional(),
  GEMINI_DEFAULT_MODEL: Joi.string().default('gemini-pro'),
  ANTHROPIC_API_KEY: Joi.string().optional(),
  CLAUDE_DEFAULT_MODEL: Joi.string().default('claude-sonnet-4'),
  OLLAMA_URL: Joi.string().optional(),
  OLLAMA_DEFAULT_MODEL: Joi.string().default('llama3'),
  AZURE_OPENAI_ENDPOINT: Joi.string().optional(),
  AZURE_OPENAI_KEY: Joi.string().optional(),
  AZURE_OPENAI_DEFAULT_MODEL: Joi.string().default('gpt-4o'),
  AWS_BEDROCK_REGION: Joi.string().optional(),
  AWS_ACCESS_KEY_ID: Joi.string().optional(),
  AWS_SECRET_ACCESS_KEY: Joi.string().optional(),
  BEDROCK_DEFAULT_MODEL: Joi.string().default('claude-sonnet-4'),
});
